services:

  nestjs:
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    networks:
      - fc-pay-gateway_default
    
  nestjs-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fc_pay_antifraud
    ports:
      - 5433:5432
    networks:
      - fc-pay-gateway_default
      
networks:
  fc-pay-gateway_default:
    external: true